### ISSUE TITLE
Scanning QR codes causes the app to lock up

### ISSUE THREAD

**Issue by danlipert** [HoardInvest/hoard#101] opened 2018-07-17 10:43 UTC
- scanning invalid QR code locks app when sending ETH (https://www.qrstuff.com/images/sample.png)
- scanning valid ETH QR code locks app when sending ETH https://maker.today/img/blog/2018/01/eth-wallet-address-qr-code.jpg
- scanning valid BTC QR code locks app when sending BTC (https://chart.googleapis.com/chart?cht=qr&chs=80&chl=2N8hwP1WmJrFF5QWABn38y63uYLhnJYJYTF&chld=M|0) 

![img_2046](https://user-images.githubusercontent.com/869266/42812739-a072d7b6-89f9-11e8-91fe-5aa8d4512911.PNG)

**Comment by zachgibb** [comment] 2018-08-08 20:41
should be addressed in #140, duplicate of #138

**Closed by zachgibb** 2018-08-08 20:41 UTC
Labels: 1.7.1, bug, iOS
