### ISSUE TITLE
After sending txn - all the individual wallets show spinners instead of going to the wallet

### ISSUE THREAD

**Issue by danlipert** [HoardInvest/hoard#313] opened 2019-01-16 12:30 UTC
Aftering initiating a BTC send, all of the individual wallet screens only show a spinner. Restarting the app restores the functionality.

**Comment by danlipert** [comment] 2019-01-16 12:32
This also happens with RVN

**Comment by danlipert** [comment] 2019-01-16 12:35
Also happens with HOARD - probably also with ETH ;)

**Comment by zachgibb** [comment] 2019-01-16 22:14
i'm pretty sure this will be fixed by, but i would love to get a confirmation of this once a build goes out #321

**Comment by zachgibb** [comment] 2019-01-16 22:17
also, this issue is a duplicate of #299

**Closed** 2019-01-16 22:17 UTC
Labels: 1.16, BTC, bug
